version: "3.9"
services:
  web:
    container_name: node
    image: node:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    working_dir: /app/cours
    ports:
      - "8085:8000"
      - "35729:35729"
    volumes:
      - .:/app
      #-.:/workspace:cached
